import type { CaseScenario } from './types';

export const scenarios: CaseScenario[] = [
  {
    id: 'case-mva',
    title: 'Accident de la route — choc frontal',
    description:
      "Un véhicule a percuté un arbre sur une route départementale. Le conducteur est conscient mais bloqué au volant. Un témoin a alerté les secours.",
    location: 'RD28, km 12, sortie de Plouvenez',
    time: '14h32',
    patient: {
      age: 34,
      sex: 'M',
      name: 'M. L.',
      history: 'Aucun antécédent médical connu. Ne prend pas de traitement. Pas d\'allergie connue.',
    },
    chiefComplaint: 'Douleur thoracique et au bassin, difficulté à respirer',
    sceneDescription:
      "Le véhicule, une berline grise, est encastré frontalement contre un platane. Le pare-brise est fissuré, le volant déformé. Le conducteur, ceinture attachée, est coincé au volant. Les airbags ont été déployés. Un témoin, passant, attend à côté du véhicule.",
    sceneHazards: ['Risque d\'incendie (fuite de carburant)', 'Trafic non sécurisé', 'Risque d\'explosion airbag'],
    expectedVitals: {
      consciousness: 'verbal',
      respiratoryRate: 28,
      heartRate: 124,
      bloodPressureSystolic: 96,
      bloodPressureDiastolic: 60,
      spo2: 91,
      temperature: 36.8,
      capillaryRefill: 4,
      pupils: 'asymmetric',
      skin: 'pale',
      painScale: 8,
      glucose: 1.1,
    },
    expectedExamination: {
      airway: 'clear',
      breathing: 'labored',
      circulation: 'weak',
      traumaHead: false,
      traumaNeck: false,
      traumaChest: true,
      traumaAbdomen: false,
      traumaPelvis: true,
      traumaLimbs: true,
      traumaBack: false,
      bleedingExternal: true,
      fracturesVisible: true,
      burns: false,
    },
    expectedAssessment: {
      mechanism: 'Choc frontal à haute cinétique, ceinture de sécurité, volant déformé',
      lesions: 'Trauma thoracique (volet costal probable), fracture du bassin, fracture du fémur droit, état de choc hémorragique',
      severity: 'unstable',
      priority: 'P1',
    },
    hints: {
      dispatch: ['Sécurisez la zone avant toute chose', 'Évaluez les risques incendie', 'Demandez un désincarcération'],
      scene: ['Le volant déformé signe un traumatisme thoracique', 'La fuite de carburant impose un extincteur'],
      vitals: ['La FR élevée et la SpO2 basse signent une détresse respiratoire', 'L\'asymétrie pupillaire peut indiquer un traumatisme crânien', 'La glycémie basse peut aggraver l\'état'],
      examination: ['Le volet costal est probable devant le trauma thoracique', 'Le bassin est instable — ne pas mobiliser', 'Le fémur fracturé explique la pâleur'],
      assessment: ['Le mécanisme est à haute cinétique', 'L\'état de choc justifie la priorité P1'],
      call15: ['Transmettez clairement le mécanisme et la gravité', 'Précisez la nécessité de désincarcération'],
      summary: ['L\'ensemble des lésions justifie un transport médicalisé'],
    },
  },
  {
    id: 'case-cardiac',
    title: 'Douleur thoracique — homme de 58 ans',
    description:
      "Un homme ressent une douleur constrictive dans la poitrine depuis 30 minutes, irradiant dans le bras gauche. Il est chez lui, assis sur son canapé.",
    location: '12 rue des Lilas, 2e étage, Appartement 4B',
    time: '06h15',
    patient: {
      age: 58,
      sex: 'M',
      name: 'M. D.',
      history: 'Hypertension, tabagisme actif (30 PA), père décédé d\'un infarctus à 60 ans. Traitement : amlodipine.',
    },
    chiefComplaint: 'Douleur thoracique constrictive irradiant au bras gauche, sueurs, nausées',
    sceneDescription:
      "Le patient est assis dans son salon, pâle et en sueurs. Il serre le poing sur sa poitrine. Un verre d\'eau est renversé à côté. Sa femme est présente et très anxieuse.",
    sceneHazards: ['Accès difficile (2e étage sans ascenseur)', 'Stress de l\'entourage'],
    expectedVitals: {
      consciousness: 'alert',
      respiratoryRate: 24,
      heartRate: 98,
      bloodPressureSystolic: 150,
      bloodPressureDiastolic: 95,
      spo2: 94,
      temperature: 36.5,
      capillaryRefill: 3,
      pupils: 'normal',
      skin: 'pale',
      painScale: 7,
      glucose: 1.4,
    },
    expectedExamination: {
      airway: 'clear',
      breathing: 'normal',
      circulation: 'normal',
      traumaHead: false,
      traumaNeck: false,
      traumaChest: false,
      traumaAbdomen: false,
      traumaPelvis: false,
      traumaLimbs: false,
      traumaBack: false,
      bleedingExternal: false,
      fracturesVisible: false,
      burns: false,
    },
    expectedAssessment: {
      mechanism: 'Suspect d\'un syndrome coronarien aigu (SCA ST+ probable)',
      lesions: 'Douleur thoracique constrictive, irradiation bras gauche, diaphorèse, nausées — syndrome coronarien aigu',
      severity: 'potentially_unstable',
      priority: 'P1',
    },
    hints: {
      dispatch: ['Rassurez l\'entourage', 'Préparez l\'évacuation par les escaliers'],
      scene: ['Le patient est conscient — laissez-le assis', 'La douleur irradiante est un signe typique du SCA'],
      vitals: ['La TA élevée et la douleur typique évoquent un SCA', 'L\'ECG est indispensable — réalisez un tracé', 'La SpO2 à 94% justifie une O2thérapie modérée'],
      examination: ['Pas de traumatisme — examen médical complet', 'Auscultez le cœur et les poumons'],
      assessment: ['Le diagnostic est un SCA probable', 'La priorité est P1 pour transport médicalisé'],
      call15: ['Demandez une médicalisation (SMUR)', 'Précisez le délai d\'apparition de la douleur'],
      summary: ['Le transport doit être médicalisé vers une USIC'],
    },
  },
  {
    id: 'case-anaphylaxis',
    title: 'Choc anaphylactique — piqûre de guêpe',
    description:
      "Une femme de 42 ans s'est fait piquer par une guêpe dans un jardin. Elle présente des plaques rouges qui s'étendent et des difficultés respiratoires.",
    location: 'Jardin public, près du terrain de jeux',
    time: '15h45',
    patient: {
      age: 42,
      sex: 'F',
      name: 'Mme R.',
      history: 'Allergie connue aux venins d\'hyménoptères (guêpe). A un stylo d\'adrénaline (Anapen) non utilisé.',
    },
    chiefComplaint: 'Démangeaisons généralisées, gonflement du visage, difficulté à respirer',
    sceneDescription:
      "La patiente est assise sur un banc, agitée. Son visage est gonflé (lèvres et paupières), son cou semble enflé. Des plaques rouges (urticaire) couvrent ses bras et son torse. Le dard de la guêpe est visible sur son avant-bras.",
    sceneHazards: ['Présence de guêpes à proximité', 'Risque d\'aggravation rapide'],
    expectedVitals: {
      consciousness: 'alert',
      respiratoryRate: 32,
      heartRate: 130,
      bloodPressureSystolic: 78,
      bloodPressureDiastolic: 45,
      spo2: 88,
      temperature: 37.2,
      capillaryRefill: 5,
      pupils: 'normal',
      skin: 'flushed',
      painScale: 3,
      glucose: 1.2,
    },
    expectedExamination: {
      airway: 'partially_obstructed',
      breathing: 'labored',
      circulation: 'weak',
      traumaHead: false,
      traumaNeck: false,
      traumaChest: false,
      traumaAbdomen: false,
      traumaPelvis: false,
      traumaLimbs: false,
      traumaBack: false,
      bleedingExternal: false,
      fracturesVisible: false,
      burns: false,
    },
    expectedAssessment: {
      mechanism: 'Réaction anaphylactique suite à une piqûre de guêpe',
      lesions: 'Choc anaphylactique : urticaire généralisée, angio-oedème, bronchospasme, hypotension',
      severity: 'critical',
      priority: 'P1',
    },
    hints: {
      dispatch: ['Éloignez la patiente de la zone de guêpes', 'Préparez l\'adrénaline immédiatement'],
      scene: ['L\'angio-oedème menace les voies aériennes', 'L\'Anapen doit être administré en urgence'],
      vitals: ['La TA effondrée et la tachycardie signent le choc', 'La SpO2 basse justifie l\'O2 à haut débit', 'L\'adrénaline IM est le traitement de première ligne'],
      examination: ['Vérifiez la perméabilité des voies aériennes', 'Recherchez le dard et retirez-le'],
      assessment: ['Le diagnostic est un choc anaphylactique', 'La priorité est P1 — urgence vitale absolue'],
      call15: ['Demandez un SMUR en urgence', 'Précisez le mécanisme anaphylactique et l\'adrénaline administrée'],
      summary: ['L\'adrénaline IM doit être administrée sans délai'],
    },
  },
  {
    id: 'case-fall-elderly',
    title: 'Chute de sa propre hauteur — personne âgée',
    description:
      "Une femme de 82 ans a fait une chute dans sa cuisine. Elle ne peut plus se relever. Sa voisine a entendu du bruit et est intervenue.",
    location: 'Résidence Les Tilleuls, Bâtiment C, Appartement 12',
    time: '10h20',
    patient: {
      age: 82,
      sex: 'F',
      name: 'Mme B.',
      history: 'Ostéoporose, hypertension, arthrose, port d\'un pacemaker. Vit seule. Traitement : bisoprolol, furosémide, calcium-vitamine D.',
    },
    chiefComplaint: 'Douleur intense à la hanche gauche, ne peut plus bouger',
    sceneDescription:
      "La patiente est allongée sur le carrelage de la cuisine, consciente. Un tabouret est renversé. Elle a froid et tremble. Sa voisine est avec elle et lui a mis une couverture.",
    sceneHazards: ['Sol glissant', 'Risque d\'hypothermie', 'Mobilier instable'],
    expectedVitals: {
      consciousness: 'alert',
      respiratoryRate: 20,
      heartRate: 88,
      bloodPressureSystolic: 135,
      bloodPressureDiastolic: 80,
      spo2: 95,
      temperature: 35.6,
      capillaryRefill: 4,
      pupils: 'normal',
      skin: 'pale',
      painScale: 9,
      glucose: 1.3,
    },
    expectedExamination: {
      airway: 'clear',
      breathing: 'normal',
      circulation: 'normal',
      traumaHead: true,
      traumaNeck: false,
      traumaChest: false,
      traumaAbdomen: false,
      traumaPelvis: true,
      traumaLimbs: true,
      traumaBack: false,
      bleedingExternal: false,
      fracturesVisible: true,
      burns: false,
    },
    expectedAssessment: {
      mechanism: 'Chute de sa propre hauteur avec traumatisme direct sur la hanche',
      lesions: 'Fracture du col fémoral gauche probable, hématome pariétal sans perte de connaissance initiale, hypothermie modérée',
      severity: 'potentially_unstable',
      priority: 'P2',
    },
    hints: {
      dispatch: ['Protégez du froid', 'Bilan complet avant mobilisation'],
      scene: ['La chute est mécanique, pas de malaise initial', 'Vérifiez le pacemaker et le traitement'],
      vitals: ['La température basse justifie un réchauffement', 'La douleur est intense — évaluez la EVA', 'La glycémie est utile chez la personne âgée'],
      examination: ['La hanche est douloureuse et raccourcie — fracture du col', 'L\'hématome crânien impose une surveillance neuro'],
      assessment: ['Le mécanisme est simple mais la patiente est fragile', 'La priorité est P2 — transport en urgence relative'],
      call15: ['Précisez l\'âge, le terrain et la fracture probable', 'Demandez un transport médicalisé vu le terrain'],
      summary: ['La fracture du col fémoral nécessite une prise en charge orthopédique'],
    },
  },
];
